### ISSUE TITLE
Exclude certain route from requiring authentication

### ISSUE THREAD

**Issue by vertangelx** [zimme/meteor-iron-router-auth#16] opened 2015-03-26 12:58 UTC
This seems like a very simple question, sorry for that!~

How do I exclude a route like `browse` from needing user to be authenticated? Tried using `except` but that does not seem to work.

	Router.configure({
		layoutTemplate: 'layout'
	});

	Router.map(function() {
		this.route('login', {
			path: '/login',
			layoutTemplate: 'layoutLogin'
		}),

		this.route('browse', {
			path: '/browse'
		})
	})

	Router.plugin('auth');

	Router.configure({
		authenticate: {
			route: 'login'
		},
		except: ['browse']
	});

**Comment by zimme** [comment] 2015-03-26 16:45
The problem is in where you configure the plugin. I'll give you a couple of examples to make things a bit more obvious for you.
```js
Router.configure({
  authenticate: {
    route: 'signIn'
  },
  layoutTemplate: 'layoutTemplate'
});
```
The above example configures `iron:router` to use a general `layoutTemplate` named `'layoutTemplate'` but it also configures the `authenticate` hook from this package on a "global" level. This is mostly intended for when you use the hooks separately from the plugin. i.e. when you attach the `authenticate` hook with `onBeforeAction` on a specific route, in the route definition.

In your case you would use the plugin configuration instead.
```js
Router.plugin('auth', {
  authenticate: {
    route: 'login'
  ,
  except: ['login', 'browse'] // In the future you won't have to except the login route because I'll automagically except the route option if provided
});
```
As you can see I'm configuring the plugin on the "plugin" level instead of globally.

**Comment by zimme** [comment] 2015-03-26 16:46
I'll close this and you can reopen the issue if you're still having trouble once you've tried moving the configuration.

**Closed by zimme** 2015-03-26 16:46 UTC
